### PR TITLE
fix: invalid cmds; authorize-operator, create-sto, revoke-opreator

### LINKED ISSUE #44: SetDocuments using 'currencyid' to json/bson
## Expected Behavior

Using `currency` instead of `currencyid` to SetDocuments json/bson.

## Actual Behavior

https://github.com/ProtoconNet/mitum-sto/blob/b05af16f753bd4d50a9f08e5a78d3c94c6fcbb0a/sto/set_documents_json.go#L19

## Steps to Reproduce the Problem

omit

## Specifications

  - commit; ProtoconNet/mitum-sto@b05af16
  - os; mac ventura
  - go version; go1.19

### PR DESCRIPTION
**Pull request by wyuinche**
### Pull-request Type (fix, feat, bug, doc, chore, test, etc...) 

- fix

### Current Behavior (Link to an open issue)

- Close #44 
- invalid commands; authorize-operator, create-sto, revoke-operator

### New Behavior (if this is a feature change)

- fix set-document field names in json/bson
- fix some commands

### CODE REVIEW

File: cmds/operation.go [hunk 1]
```diff
@@ -13,11 +13,11 @@ type OperationCommand struct {
...
-	TransferSecurityTokensPartition TransferSecurityTokensPartitionCommand             `cmd:"transfer-security-token" help:"transfer security tokens by partition"`
-	RedeemTokens                    RedeemTokensCommand                                `cmd:"redeem-tokens" help:"redeem tokens from tokenholder"`
+	TransferSecurityTokensPartition TransferSecurityTokensPartitionCommand             `cmd:"" name:"transfer-security-token" help:"transfer security tokens by partition"`
+	RedeemTokens                    RedeemTokensCommand                                `cmd:"" name:"redeem-token" help:"redeem tokens from tokenholder"`
 	AuthorizeOperators              AuthorizeOperatorsCommand                          `cmd:"" name:"authorize-operator" help:"authorize operator"`
 	RevokeOperators                 RevokeOperatorsCommand                             `cmd:"" name:"revoke-operator" help:"revoke operator"`
-	SetDocuments                    SetDocumentsCommand                                `cmd:"" name:"set-documents" help:"set sto documents"`
+	SetDocuments                    SetDocumentsCommand                                `cmd:"" name:"set-document" help:"set sto documents"`
```
Comment (soonkuk) [inline cmds/operation.go:20]: @wyuinche It is also necessary to change the name of SetDocuments operation to SetDocument.

**Review by soonkuk — CHANGES_REQUESTED** [review]

File: cmds/operation.go (hunk 1 above)
Comment (wyuinche) [reply cmds/operation.go]: @soonkuk All names `SetDocuments` have been replaced with `SetDocument`.

**Review by soonkuk — APPROVED** [review]
Good!

**Review by soonkuk — APPROVED** [review]
