### PR TITLE
fix: prevent register operator with zero partition balance

### LINKED ISSUE #55: Not allow to register operators with zero partition balance
## Expected Behavior

authorize-operator cannot be processed when the partition balance of the account is zero.

## Actual Behavior

No validation of partition balance.

## Steps to Reproduce the Problem

omit

## Specifications

  - commit; ProtoconNet/mitum-sto@59fff4c82f315ee2fbc9b5c64e570443ceaa42d7
  - os; macos ventura
  - go version; go1.19

### PR DESCRIPTION
**Pull request by wyuinche**
### Pull-request Type (fix, feat, bug, doc, chore, test, etc...) 

- fix

### Current Behavior (Link to an open issue)

- Close #55 

### New Behavior (if this is a feature change)

- authorize-operator processor updated

### CODE REVIEW

File: sto/authorize_operators_process.go [hunk 1]
```diff
@@ -54,6 +54,30 @@ func (ipp *AuthorizeOperatorsItemProcessor) PreProcess(
...
+		if p == it.Partition() {
+			break
+		}
+
+		if i == len(partitions)-1 {
+			return errors.Errorf("partition not in tokenholder partition list, %s-%s, %s", ipp.sender, it.Contract(), it.STO(), it.Partition())
+		}
+	}
+
+	balance, err := existsTokenHolderPartitionBalance(it.Contract(), it.STO(), ipp.sender, it.Partition(), getStateFunc)
```
Comment (soonkuk) [inline sto/authorize_operators_process.go:72]: @wyuinche If the partition is not presented in TokenHolderPartitionStateValue, does it mean that the partition balances is zero? Should we check again to confirm that the partition balance is indeed zero?

Comment (wyuinche) [reply sto/authorize_operators_process.go:72]: @soonkuk I just put it in for double checking. The code that checks the partition balance after checking the list of partitions can be removed if it is logically unnecessary.

Comment (soonkuk) [reply sto/authorize_operators_process.go:72]: @wyuinche I think we can't do anything even if partition balance is not zero. Because two evidence show the opposite fact and we can't decide which is true result. So I think the checking TokenHolderPartitionsStateValue is enough.

Comment (wyuinche) [reply sto/authorize_operators_process.go]: @soonkuk It's modified!

**Review by soonkuk — APPROVED** [review]
